#!/bin/bash
# get rlwrap here: http://utopia.knoware.nl/~hlub/rlwrap/

[ -d "$HOME/.yorick/logs/" ] || eval "mkdir -p $HOME/.yorick/logs/"
rlwrap --remember -c -b "(){}[],^%$#@\"\";:''|\\" -l $HOME/.yorick/logs/yolog.`date +%F.%R` yorick
